### PR TITLE
Include waagent 2.0.16

### PR DESCRIPTION
**Pull request by waldiTM**
Instead of trying and failing to use a system supplied copy of the old agent, just include a local copy always.

### CODE REVIEW

**Comment by boumenot** [comment]
It appears that we've done the same work.  I think this is a dupe of #440.  Is there any reason to keep this PR open too?

**Comment by waldiTM** [comment]
You still need to remove the code to every try to open /usr/sbin/waagent

**Comment by waldiTM** [comment]
Also, how can it a dupe if it fixes all, instead of only one of the included extensions?

**Comment by boumenot** [comment]
There are more extensions in this repo than the ones called out in the Makefile, so the change covers more than VMAccessForLinux.  I am not going to remove the other code because it is shared among most of the extensions in this repo.

**Pull request closed without merging**
