### PR TITLE
[LAD] Support dynamic mdsd port

### PR DESCRIPTION
**Pull request by hosungsmsft**
@jasonzio, @LiweiPeng - Please review. Thanks.

### CODE REVIEW

**Comment by LiweiPeng** [comment]
for the line 638, is '-q' a new option to mdsd? I didn't see it in latest 'develop' branch code.

**Comment by hosungsmsft** [comment]
Yes. '-q' is the newest option added specifically for this purpose. Please see our internal CodeFlow code review for this mdsd code change.

**Comment by LiweiPeng** [comment]
Thanks Hosung.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by hosungsmsft** [comment]
@LiweiPeng & @jasonzio - New change pushed reflecting the ongoing mdsd design change on default bind() behavior.

**Comment by LiweiPeng** [comment]
looks good to me.

**Pull request merged**
