### PR TITLE
remove all non ade files

### PR DESCRIPTION
**Pull request by bamuir**
Delete any file not needed for ADE builds on our dualpass dev branch, in efforts to clean up our builds for CodeQL.

### CODE REVIEW

**Review by nkuchta — CHANGES_REQUESTED** [review]
This repository is shared and not specific to ADE. Please do not delete the files unrelated to ADE. If you wish, you can fork and create a new repo specific to ADE.

**Review by hestolz — DISMISSED** [review]
+1 please do not remove our code :) this repo contains various teams' vm extension code, it is not just an ade repo.

**Comment by bamuir** [comment]
@hestolz  @nkuchta  this is only in our branch of the shared repository. Why can we not delete these files that have not been touched for 6+ years? These are not related to ADE, and we are being flagged for them in our build. This branch is also never merged into Master

**Review by Jyotsna-Anand — APPROVED** [review]
LGTM

**Pull request merged**
