### PR TITLE
add almalinux and rocky linux support to agent

### PR DESCRIPTION
**Pull request by athiede-vendavo**
It is important to have a supported, free RHEL rebuild available for testing and development. Rocky and Alma are the de-facto replacements. CentOS 8 is end-of-life and can't be used. Rocky and Alma are functionally identical to CentOS 8, but they are actively supported.

https://github.com/Azure/azure-linux-extensions/issues/1482 mentions a desire for this support as well.

My request for this support in the older OMS Agent (https://github.com/microsoft/OMS-Agent-for-Linux/pull/1420) was denied, I assume because it's on its way out.

### CODE REVIEW

**Review by mobilebilly — APPROVED** [review]

**Comment by simonkeyd** [comment]
bump @hestolz @AaronRM @simathih following Alma sponsoring is there any plan on approving this ?

**Comment by Pyr0technicien** [comment]
Is there anyway to change this manually and to be able to install it on almaLinux ?
I'm not able to find this exact file on my server

**Comment by athiede-vendavo** [comment]
https://github.com/Azure/azure-linux-extensions/commit/84abcfa1a3465741916fb6452834afe7deb56617
Rocky Linux support has been merged. Hopefully Alma Linux is next in line since Alma is the one that actually provides Azure images.

**Comment by athiede-vendavo** [comment]
https://github.com/Azure/azure-linux-extensions/commit/d1f17bfc3ae8f75fbc095ef913d0c0c34e12e0e6

It's been added! Hooray! Closing this PR as it's no longer necessary.

**Pull request closed without merging**
