### PR TITLE
vmaccess: enable expiration of accounts

### LINKED ISSUE #229: add/restore support for account expiration in VMAccess extension
For some reason account expiration support not added or removed from VMAccess extension.

vmaccess.py
```
    error_string = waagent.MyDistro.CreateAccount(
        user_name, user_pass, None, None)
```

waagent
```
    def CreateAccount(self,user, password, expiration, thumbprint):
        return CreateAccount(user, password, expiration, thumbprint)
```

Sometimes it is needed to set expiration time for account but with current version it is not possible.
Looks like it was supported before since it is mentioned in [blog about VMAccess Extension](https://azure.microsoft.com/en-us/blog/using-vmaccess-extension-to-reset-login-credentials-for-linux-vm/)

### PR DESCRIPTION
**Pull request by boumenot**
Plumb the expiration value through when creating a new account.  This was documented as working, but was not actually implemented per the [docs][1].

I made a few changes based on PEP recommendations.

Closes #229

[1]: https://azure.microsoft.com/en-us/blog/using-vmaccess-extension-to-reset-login-credentials-for-linux-vm/

### CODE REVIEW

**Comment by paulmey** [comment]
We should also add it to the README.md...
LGTM otherwise

**Comment by mbearup** [comment]
LGTM

**Comment by hglkrijger** [comment]
lgtm

**Comment by jasonzio** [comment]
lgtm

**Comment by boumenot** [comment]
OMG!  It's like I have a cheering section. :open_mouth: 

Good point on the docs, I will add.

**Pull request merged**
