### PR TITLE
[LAD] Add OMI diag dump code, enable core dump

### PR DESCRIPTION
**Pull request by hosungsmsft**
@jasonzio @LiweiPeng - Please review this PR. I'm aiming at releasing LAD 2.3.9001 after this PR.

### CODE REVIEW

**Comment by jasonzio** [comment]
I don't see where you're enabling core dumps.

**Comment by hosungsmsft** [comment]
@jasonzio - The "-C" cmdline option in line 639 enables core dump.
https://github.com/Azure/azure-linux-extensions/pull/155/files#diff-8b25f5ab49f2a3a59328935d095170dfR639

**Comment by LiweiPeng** [comment]
looks good to me. sign off

**Comment by jasonzio** [comment]
lgtm

**Pull request merged**
