### PR TITLE
Replace python-future with standard python in AMA and LAD

### PR DESCRIPTION
**Pull request by NarineM**
This PR covers removal of 3rd party urllib dependency PythonCharmers that triggered s360 security bugs. With this change we will switch to standard python.
Unit tested by mocking extension calls with distros running python v3.8.10, python 2.7.5.

### CODE REVIEW

**Review by simathih — CHANGES_REQUESTED** [review]
how will we test impact across various python versions?

**Comment by simathih** [comment]
it has potential of breaking install/enable. we need to be elaborate with python version testing

**Comment by NarineM** [comment]
Added python version info that was used to test the change to this PR description. Needs to be well tested in Canary E2E as we can not rely only on testing done so far with mocking extension calls.

**Review by simathih — APPROVED** [review]

**Comment by simathih** [comment]
Ensure E2E pipeline and Canary E2E pass

**Review by D1v38om83r — DISMISSED** [review]

**Review by D1v38om83r — APPROVED** [review]

**Review by simathih — APPROVED** [review]

**Pull request merged**
