### PR TITLE
Add OmsAgent extension [WIP]

### PR DESCRIPTION
**Pull request by varunkumta**
1) Add OmsAgent extension
2) Refactor common code shared by CustomScript and OmsAgent into Utils (ScriptUtil and LogUtil)

TODO: the agent packages (within OmsAgent/packages/) and Readme.md (within OmsAgent/) are still not final. I will do another commit with the final versions and then this can be merged into Azure/master.

### CODE REVIEW

**Comment by bingosummer** [comment]
@varunkumta Thanks for your contributions.

Since your PR changes CustomScript too, we need to have some reviews and regression tests on CustomScript which may need some time.
And for the OmsAgent extension itself, you need to verify that it works.

If you have any questions, please let us know and we shall be happy to help.

**Comment by bingosummer** [comment]
Please make sure to squash your commits.

**Comment by varunkumta** [comment]
@bingosummer Thanks for the comments. I have already published (as internal) and tested my OmsAgent extension. Also, since CustomScript was re-factored to use the same Util modules as OmsAgent, I have confidence there shouldn't be any regressions. However, I will wait for your testing to be complete.
I have also squashed all my commits into one. And will squash them again once I have completed the TODO items I initially mentioned

**Comment by bingosummer** [comment]
@varunkumta 
Ping.
Have you completed the TODO items?

**Comment by varunkumta** [comment]
@bingosummer Yes, I have completed them. However, we are currently in lockdown for the holidays and will not be able to test the extension with the latest package. I will be back on 1/7 and will let you know of the latest status then.

**Comment by varunkumta** [comment]
Closing this pull request .. will send another one

**Pull request closed without merging**
