### PR TITLE
Support OS disk encryption on RHEL 7.2 & CentOS 7.2

### PR DESCRIPTION
**Pull request by krkhan**

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
@krkhan you don't have to send me email about the pr. Our team already gets notifications about these. 

Has this code been previously reviewed? If not, can you please pull your team members to review this? We'll also review comment in general about the PR itself and anything that stands out. But I'm not sure if we have bandwidth do a single-PR 1700 line change.

**Comment by ahmetalpbalkan** [comment]
I encourage sending smaller PRs next time. Also has merge conflicts. Please rebase your code and resolve those and push-f again.

**Comment by krkhan** [comment]
@ahmetalpbalkan Resolved the conflict. Please check your mail re: review.

**Comment by ahmetalpbalkan** [comment]
@krkhan I see this PR is getting larger and larger. Let us know when you get this stuff code reviewed (preferably on GitHub) and it is ready to merge.

**Comment by krkhan** [comment]
@ahmetalpbalkan I started a CR on CodeFlow last week. Will try to move new changes into a separate branch so that this PR doesn't increase in size.

**Comment by ahmetalpbalkan** [comment]
Merging as @krkhan told that the code is CR'd.

**Pull request merged**
