### PR TITLE
Lad 2.3.9017 release PR

### PR DESCRIPTION
**Pull request by hosungsmsft**
@jasonzio , @LiweiPeng : Please review. Thanks.

### CODE REVIEW

**Comment by jasonzio** [comment]
LGTM

**Comment by jasonzio** [comment]
lgtm

**Comment by LiweiPeng** [comment]
if we force to remove these 2 rpms, will this cause bad effects to customers? some customers may need them for their work.

**Comment by LiweiPeng** [comment]
signed ff

**Pull request merged**
