### PR TITLE
[LAD] Merge LAD-v.2.3.9001 commits to master for official release

### PR DESCRIPTION
**Pull request by hosungsmsft**
Major commits were already reviewed by @jasonzio and @LiweiPeng. This is a formality PR for merging to master. Confirmed that all existing E2E tests pass on all tested distros/versions. We are ready to release LAD v.2.3.9001.

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
👍

**Comment by hosungsmsft** [comment]
Just mentioning the actual sub-PRs with actual review comments. Should have used GitHub merges to show them automatically, I guess. Will try that in the future.
#159, #155, #152, #151, #148, #138, #136, #134, #133, #131 #130, #129, #126

**Comment by ahmetalpbalkan** [comment]
@hosungsmsft perhaps we should evaluate moving LAD to its own separate GitHub repository. Problem with all these extensions in this repo is, we can't really tag versions. So it's hard to identify which PR made it to which release.

Good thing is, we now have a single merge commit, merging this version of LAD to master. So people can `git checkout` to that merge commit and retrieve the code tree of the version a lot more clearly now.

**Comment by hosungsmsft** [comment]
@ahmetalpbalkan - Agreed, and it has been a question since we first started to take over extensions, starting with LAD. The sticky thing would be the Utils directory, and as I mentioned, LAD already forked out, and we may need to consider whether to merge back the forked Utils or not. I guess other extensions moving out would be based on those extension owners' choices.

**Comment by ahmetalpbalkan** [comment]
@hosungsmsft the healthiest option is to develop a common extensions utilities in a separate repository and periodically sync with that. We've seen extensions rely on `waagent` even for various [simple functionality](https://github.com/Azure/WALinuxAgent/issues/223#issuecomment-224713170) as well as complicated things like wireserver telemetry (which they probably shouldn't be doing).

Docker Extension ships with a [VM extension utils package for Go](https://github.com/Azure/azure-docker-extension/tree/master/pkg/vmextension) which are used by LinuxAsm as well as DockerExtension.

Probably decoupling waagent + utils here from all the extensions into a separate module (perhaps even on PyPi?) and moving all extensions to their own repos is easier for releasing, tagging and issue tracking. If you folks could find time to make this a reality, it would set a nice example.

**Pull request merged**
