### PR TITLE
Freeze issue

### PR DESCRIPTION
**Pull request by soumyanishan**
@ahmetalpbalkan I have removed the piece of code where it was creating the config file. Also the config file path and name changed to '/etc/azure/vmbackup.conf'

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
@soumyanishan thanks. You don't have to create a new PR next time, you can just keep pushing to your PR branch to update an existing PR. I'm merging as it is already code reviewed.

**Comment by ahmetalpbalkan** [comment]
@soumyanishan you also have a commit like:

image

in the history, let's prevent that next time. I'm squashing all these commits into one and merging because of it this time.

**Comment by soumyanishan** [comment]
@ahmetalpbalkan , I was doing my changes in a Linux VM without the git config username set. The commit before git config resulted in it

**Comment by ahmetalpbalkan** [comment]
@soumyanishan got it. Those things can always be fixed with `git rebase`, `git commit --amend --author` and `git push -f`. Feel free to practice it in your own fork since it is already merged. :-)

**Pull request merged**
