### PR TITLE
Kali Linux 2016.2 Support

### PR DESCRIPTION
**Pull request by drivelbyday**
image
image

### CODE REVIEW

**Comment by drivelbyday** [comment]
root@kali:/var/lib/waagent/Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9007# python diagnostic.py -enable
2016/09/06 11:04:37 LinuxAzureDiagnostic started to handle.
2016/09/06 11:04:37 [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9007] cwd is /var/lib/waagent/Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9007
2016/09/06 11:04:37 [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9007] Change log file to /var/log/azure/Microsoft.OSTCExtensions.LinuxDiagnostic/2.3.9007/                                                                                                                                                                 extension.log
2016/09/06 11:04:37 [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9007] sequence number is 0
2016/09/06 11:04:37 [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9007] setting file path is/var/lib/waagent/Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.90                                                                                                                                                                 07/config/0.settings
2016/09/06 11:04:37 [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9007] JSON config: {"runtimeSettings": [{"handlerSettings": {"protectedSettings": " abc123"                                                                                                                                                              9uZmlndXJhdGlvbj48L1dhZENmZz4=", "StorageAccount": "kalireleasediag562"}, "protectedSettingsCertThumbprint": "90E62E61734B70160A0968060606087C5D20E8FD"}}]}
2016/09/06 11:04:37 [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9007] Config decoded correctly.
2016/09/06 11:04:37 [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9007] Disable verbose log
2016/09/06 11:04:37 [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9007] Deployment ID found: abc123.
2016/09/06 11:04:37 [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9007] Application Insights key not found.
2016/09/06 11:04:37 [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9007] Event volume not found in config. Using default value: Medium
2016/09/06 11:04:37 [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9007] Dispatching command:-enable
2016/09/06 11:04:37 [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9007] get pid:[]
2016/09/06 11:04:37 [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9007] start daemon ['python', '/var/lib/waagent/Microsoft.OSTCExtensions.LinuxDiagnostic-2                                                                                                                                                                 .3.9007/diagnostic.py', '-daemon']
2016/09/06 11:04:47 [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9007] Enable,success,0,Enable succeeded

**Comment by jasonzio** [comment]
Hi @drivelbyday, I'm one of your friendly neighborhood Microsoft humans. Thanks for your contribution!

This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. I'm one of the real humans who will now evaluate your PR.

**Comment by hglkrijger** [comment]
lgtm

**Comment by jasonzio** [comment]
Hi @drivelbyday, I'm your friendly neighborhood Microsoft software development engineer. Thanks for your contribution!

This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans (including me) will now evaluate your PR.

Seriously, thanks.

**Comment by jasonzio** [comment]
lgtm

**Pull request merged**
