### PR TITLE
Add Debian 10 Support

### PR DESCRIPTION
**Pull request by aswatt**

### CODE REVIEW

**Review by hestolz — COMMENTED** [review]
is this added to https://github.com/Azure/azure-linux-extensions/blob/master/OmsAgent/extension-test/oms_extension_tests.py too?
Also need to update [here](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/agents-overview#linux)

**Comment by NarineM** [comment]
We need to add a new error code for gpg and define it as 55 like we have for other pre -reqs (curl, etc.) and check it first before calling installer

**Comment by aswatt** [comment]
> is this added to https://github.com/Azure/azure-linux-extensions/blob/master/OmsAgent/extension-test/oms_extension_tests.py too? Also need to update [here](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/agents-overview#linux)

For oms_extension_tests.py, it looks like we're missing several newer distros (ubuntu 20, rhel / centos / oracle 8, etc), should I add those in with this PR as well or should we make a separate PR to add all the missing distros?

**Comment by aswatt** [comment]
Debian 10 support added in separate PR (https://github.com/Azure/azure-linux-extensions/pull/1540), closing out this PR.

**Comment by aswatt** [comment]
Debian 10 support added in separate PR (https://github.com/Azure/azure-linux-extensions/pull/1540), closing out this PR.

**Pull request closed without merging**
