### PR TITLE
Add config option for dist-upgrade style patching

### PR DESCRIPTION
**Pull request by mbearup**

### CODE REVIEW

**Comment by jasonzio** [comment]
LGTM

**Comment by jasonzio** [comment]
lgtm

**Comment by thomas1206** [comment]
Matt, could you also update ReadMe for the new option?

**Comment by mbearup** [comment]
Thanks Thomas, I've updated the readme file.

**Comment by bingosummer** [comment]
Running some tests. Will merge it after passing the test.

**Pull request merged**
