### PR TITLE
Refactored OmsAgent Extension readme examples in section 2.2 to reference current az cli

### PR DESCRIPTION
**Pull request by larryms**

### CODE REVIEW

**Comment by larryms** [comment]
Any chance this PR to the documentation can get merged?  I'd like to see the reference(s) to the classic CLI removed as it has been deprecated per https://docs.microsoft.com/en-us/cli/azure/install-classic-cli?view=azure-cli-latest

**Comment by larryms** [comment]
@hestolz could you approve this PR to the documentation?

**Comment by hestolz** [comment]
@shkhisti @simathih who have write privileges

**Comment by larryms** [comment]
@shkhisti @simathih checking on this PR

**Comment by hestolz** [comment]
@larryms sorry for the huge delay here. I have just 1 nit, for consistency you should change the ordering for 2.2 such that it matches 2.1. That is, resource manager is x.x.1, classic is x.x.2

**Comment by larryms** [comment]
@hestolz I made your suggested change

**Pull request merged**
